### ISSUE TITLE
Origin of merge groups

### ISSUE THREAD

**Issue by Quintus** [OGRECave/blender2ogre#105] opened 2021-05-23 14:26 UTC
Hi all!

Which is the rule blender2ogre uses to determine the origin of a merge group? I've experimented a little and I think the rule is "it's the origin of the last object added into the collection", but it'd be nice to have that confirmed (with a note in the README maybe).

  -quintus

**Comment by sercero** [comment] 2021-05-23 21:02
I think that the origin should be the center of geometry of all the merged objects.

The code just uses the Blender join to join all the meshes so it is as you say, the origin of the mesh ends up being the same as the last one added to the collection.

This can be solved by calling bpy.ops.object.origin_set(type='ORIGIN_GEOMETRY') after joining the meshes, and could be configurable because there are several options for recalculating the origin of the mesh.

@paroj what do you think?

**Comment by paroj** [comment] 2021-05-24 00:00
> I think that the origin should be the center of geometry of all the merged objects.

well, sometimes you want to exactly specify the origin - like the when tyres of the car should touch the ground plane.

If you join the whole car and then use the center off mass as origin this wont work.

Preferably, I would like to keep away from the whole centering thing and just document the current behavior in the readme. Maybe add a hint that if you prefix your object with "Z" blender will use its origin.

**Comment by sercero** [comment] 2021-06-15 17:45
@paroj I have been doing tests regarding this issue and what @Quintus says is true, the last object added is the one that determines where the origin for the merged object ends up.

The problem is that if you reload the blend file, the order of the objects changes (not randomly, but different to the one you set up) so it is not possible to document this consistently.

What I found, and I think is a good solution is to use this:
![image](https://user-images.githubusercontent.com/5248597/122098918-d0d9b480-cde7-11eb-90d8-d6dbd64237f7.png)

I have implemented a change that sets the origin of the merged object as the values set in the dupli_offset.

But I am only setting it, if they are different from (0, 0, 0) so that we don't have to put another switch for this and people who don't care just leave things as they are.

If someone wants to use the origin they can put (0.001, 0.001, 0.001) or something like that.

What do you think?

Should we add a switch for this?

**Comment by Quintus** [comment] 2021-06-15 17:57
Thanks for looking into it. As for my part, I am indifferent to the
actual solution, just as long as it is documented somewhere.

  -quintus

-- 
Dipl.-Jur. M. Gülker | https://mg.guelker.eu |    For security:
Passau, Germany      | ***@***.***    | () Avoid HTML e-mail
European Union       | PGP: see homepage     | /\ http://asciiribbon.org

**Comment by paroj** [comment] 2021-06-15 18:23
> But I am only setting it, if they are different from (0, 0, 0) so that we don't have to put another switch for this and people who don't care just leave things as they are.

sounds good! I dislike additional switches as you know :wink:

**Comment by paroj** [comment] 2021-06-16 11:08
fixed by #110

**Closed by paroj** 2021-06-16 11:08 UTC
