### ISSUE TITLE
.xml importer for blender 2.8/2.9 ?

### ISSUE THREAD

**Issue by vido89** [OGRECave/blender2ogre#60] opened 2021-02-18 13:03 UTC
Are we gone get .xml importer for blender 2.8/2.9x ?

**Comment by paroj** [comment] 2021-02-19 00:41
Are u gone write one?

**Comment by vido89** [comment] 2021-02-20 14:37
I would like but Im not dev I dont know python :)

**Comment by sercero** [comment] 2021-05-13 01:16
@paroj I have been looking into this: there is an importer by Daniel Wickert (Haffax) [Blender importer [WIP]](https://forums.ogre3d.org/viewtopic.php?t=9135), that has been extended by liyonghelpme (https://gist.github.com/liyonghelpme/7b69abc8d0feb8decd65) to incorporate many features that were missing from the original and also adecuate the script to Blender 2.7x (don't know how much work for 2.8+ yet, materials could be tough).

Do you think it makes sense to try and incorporate that script into blender2ogre or it would be better to create a new project like ogre2blender?

1) Incorporate that script into blender2ogre
It has the advantage that some options are the same (OgreXMLConverter path, Logging, Axis swapping)

2) Create a new project like ogre2blender
Could be less work, but I'm not sure because I am seeing that many structures from blender2ogre have to be replicated to have similar desirable features like a final report, configurable options from UI.

**Comment by paroj** [comment] 2021-05-13 01:19
I would rather start with the Kenshi code #36, which already has geometry working for 2.7x and 2.8x

**Comment by sercero** [comment] 2021-05-13 03:34
There is another one as well: https://github.com/lamogui/ogre_blender_importer

That crazy guy reimplemented in python the Ogre C++ classes that import the meshes, its pretty advanced and also very difficult to follow.

I will check the Kenshi importer.

**Comment by sercero** [comment] 2021-05-13 11:51
@paroj you are right, the design of the Kenshi importer is much better but you didn't answer my original question 😅

Should the importer be integrated into blender2ogre or perpahs create a new project?

I think its better to integrate the importer into blender2ogre to take advantage of the infrastructure that the exporter already has.

**Comment by paroj** [comment] 2021-05-13 12:12
> I think its better to integrate the importer into blender2ogre to take advantage of the infrastructure that the exporter already has.

yes, I agree. Also, most other blender plugins work that way.

**Comment by sercero** [comment] 2021-06-07 00:53
Hey @paroj, I'm having trouble with the skeleton importing part.

The problem is that it seems that Ogre bones are just a location and a rotation, no length provided.

But in Blender, bones have a head and a tail.

The only way I found to somewhat assign a head and tail to the bones is when you have a hierarchy to have the parent location as the head and the child location as the tail and then the bone name is that of the parent.

BUT, what happens when a parent has many children?
How could I determine which child is the tail?

Do you know a way to solve this conundrum?

I'm having trouble following the logic of the Kenshi importer, all that complication and it does not even work... tried with the ninja and fish models that come with the Ogre samples and both skeletons are badly imported, some bones are OK but others are facing the wrong direction (the ninja is the one that looks the worst) or have random size.

I'm redoing the skeleton importing and I've had success in producing good skeletons for these models but there is the naming problem and also problem Nº2:

Bones that have no children... It seems that it is impossible to assign a tail to these bones.
The Kenshi importer seems to go through all the bones, get an average length and assign that length to the bones without children. This does not seem to be a very good solution in my opinion.

What do you think? Is it a lost cause?

**Comment by sercero** [comment] 2021-06-08 19:01
@paroj I don't want to spend too much time on this so I will use the skeleton import from the Kenshi Importer, the code is ugly and the result is also ugly (the bones are too small for the ninja model for example).

But the good thing about the skeleton generated by the Kenshi importer is that you can just parent the mesh to the skeleton and the vertex groups created by the importer work as intended wich was not the case with the skeleton created by my code.
Another good thing is that the uglyness can be mitigated by selecting 'Stick' bones.

If we use the skeleton generated by my code it looks like a proper rig made in Blender, but you have to parent it with automatic weights (or paint them yourself) because the vertex groups don't work properly.
Also you have to rename some bones and adjust the ones with no children, so in the end it is best to use the one from the Kenshi importer.

![image](https://user-images.githubusercontent.com/5248597/121241233-97e29280-c871-11eb-8c30-9fda3bc0627c.png)
On the left is the result of the Kenshi importer and on the right the result of my code.

I looked into all the importers available to see if there are alternative implementations:
 - [Importer from lamogui](https://github.com/lamogui/ogre_blender_importer). This importer reimplmentes the Ogre C++ classes in python, its pretty insane the work done here. But it is not very usable.
 - [Torchlight to Blender](https://code.google.com/archive/p/torchlight-to-blender/downloads). Importer made for Torchlight the code is *very* similar to the Kenshi Importer
 - [Upgrades made by liyonghelpme](https://gist.github.com/liyonghelpme/2cd3c0135facd8f89878). Upgrades to the original Daniel Wickert (Haffax) importer from 2005.

So in the end we have two types of DNA: the lamogui importer which reimplmentes the Ogre C++ classes in python and is incomplete
And the importers derived from the original work made by Daniel Wickert (Haffax): Kenshi, TorchLight importer and liyonghelpme, where most of the work seems to have been done by @liyonghelpme

**Comment by paroj** [comment] 2021-06-14 11:25
fixed with  #109

**Closed by paroj** 2021-06-14 11:25 UTC

**Comment by sercero** [comment] 2021-06-14 17:58
@vido89 we have already incorporated an importer into the proyect.

If you want you can take a look at the new importing feature.

Download the master branch and install acording to the README instructions.

Then just go to `File->Import->Ogre3D (.mesh)` and select the mesh you want to import.

**Comment by vido89** [comment] 2021-06-14 20:01
@sercero Thanks for update :)
